### ISSUE TITLE
Replace zopim with custom solution

### ISSUE THREAD

**Issue by lsolesen** [vih/sport_2014#5]
Instead of the Zopim slidein-contact, I want to substitute this with something that looks like play.tv2.dk with the label "Kontakt" which in turn opens http://vih.dk/formular/kontakt (maybe in a slidein modal)?

**Comment by mglaman** [comment]
@lsolesen 
- this is to replace the popup contact widget with an existing node, correct? 
- you'd rather it open a regular modal rather than just slide up a tab - correct?

If the above is correct, we could implement the link as a ctools modal trigger which opens the form. When the form completes it closes. This way no need to add Colorbox or some other library.

Note: Not seeing what the example on play.tv2.dk would quite be

**Comment by lsolesen** [comment]
play.tv2.dk seems to have removed the feature, they were using. I am guessing that a ctools modal will be allright. It should open a webform.

The top bar is a kind of a call for action to contact us - and the zopim is also a cta for contacting us. It seems that the zopim contact form gives us some extra contacts. 

What would you think would work the best?
